//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Repository
{
    using Component.Data;
    using System;
    using System.Collections.Generic;
    
    public partial class RoleUser : EntityBase<int>
    {
        public override int SysNo { get; set; }
        public int RoleSysNo { get; set; }
        public int UserSysNo { get; set; }
        public int Status { get; set; }
        public System.DateTime InDate { get; set; }
        public string InUserName { get; set; }
        public int InUserSysNo { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string EditUserName { get; set; }
        public Nullable<int> EditUserSysNo { get; set; }
    }
}
